name: eventtracker_app
description: Application de gestion d'événements

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  image_picker: ^1.0.7 
  # État et logique
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  intl: ^0.19.0
  
  # Utilitaires
  url_launcher: ^6.2.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700